/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.snake;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JLabel;

/**
 *
 * @author alu13114532
 */
public class ScoreBoard extends javax.swing.JPanel {

    private int scoreBoard = 0;

    public int getScoreBoard() {
        return scoreBoard;
    }

    public void setScoreBoard(int scoreBoard) {
        this.scoreBoard = scoreBoard;
    }
    
    private JLabel label;
    
    public ScoreBoard() {
        setLayout(new FlowLayout());
        label = new JLabel();
        add(label);
        scoreBoard = 0;
        updateScoreBoard();
        setPreferredSize(new Dimension(100,30));
        label.setFont(new Font("Oswald", Font.BOLD, 20));
        label.setForeground(Color.BLACK);

    }
    
    public void incrementFood() {
        scoreBoard++;
        updateScoreBoard();
    }
    
    public void incrementSpecialFood() {
        scoreBoard = scoreBoard + 3;
        updateScoreBoard();
    }
    
    public void updateScoreBoard() {
        label.setText(ConfigData.getInstance().getPlayerName() + " Score: " + scoreBoard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
